example: example.c ../src/led/led.c ../src/dma/dma.c ../src/gpio/gpio.c ../src/util/util.c ../src/vc-memory/vc-memory.c ../src/mailbox/mailbox.c ../src/mailbox/util.c
	gcc -o example example.c ../src/led/led.c ../src/dma/dma.c ../src/gpio/gpio.c ../src/util/util.c ../src/vc-memory/vc-memory.c ../src/mailbox/mailbox.c ../src/mailbox/util.c

