blink: blink.c ../../src/led/led.c ../../src/dma/dma.c ../../src/gpio/gpio.c ../../src/util/util.c ../../src/vc-memory/vc-memory.c ../../src/mailbox/mailbox.c ../../src/mailbox/util.c
	gcc -o blink blink.c ../../src/led/led.c ../../src/dma/dma.c ../../src/gpio/gpio.c ../../src/util/util.c ../../src/vc-memory/vc-memory.c ../../src/mailbox/mailbox.c ../../src/mailbox/util.c

